### ISSUE TITLE
I have a question  Expected u.is_cuda() to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)

### ISSUE THREAD

**Issue by Rooike111** [txchen-USTC/MiM-ISTD#14]
Expected u.is_cuda() to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
OMG This question,I can't resolve. can you help me? please

**Comment by Rooike111** [comment]
> Have you solved this problem yet? I'm having the same problem.

OH yes  ，put your data on cuda than it can run 
like this
if __name__ == '__main__':
    
    input_ = torch.Tensor(5, 3, 256, 256).cuda()
    net = MiM([2]*3,[8, 16, 32, 64, 128]).cuda()
    
    out=net(input_)

**Comment by darkmingy** [comment]
ok, I get it! thanks!
